# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

name: Build one
on:
  workflow_call:
    inputs: &reusable_inputs
      os:
        type: string
        required: true
      cibw_os:
        type: string
        required: true
      cibw_arch:
        type: string
        required: true
      cibw_py_ver:
        type: string
        default: 'cp314'
      # condition:
      #   type: boolean
      #   default: true
  workflow_dispatch:
    inputs: *reusable_inputs

jobs:
  
  build_one:
    name: ${{ inputs.cibw_os }}_${{ inputs.cibw_arch }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    # if: ${{ inputs.condition }}
    
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      
      - name: Set up QEMU
        if: ${{ !(inputs.cibw_arch == 'x86_64' || inputs.cibw_arch == 'aarch64') }}
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      
      - name: Download clang image
        if: ${{ endsWith(inputs.cibw_os, 'linux') && contains(fromJson('["ppc64le","riscv64","loongarch64","s390x"]'), inputs.cibw_arch) }}
        run: bash ./utils/install-static-clang.sh -d ./clang_image -m download-only
      
      - name: Build wheels
        uses: loong64/cibuildwheel@e2eb224eba52e082e342e0d7d7e1443a22a170f2 # v4.1.0
        env:
          CIBW_BUILD: "${{ inputs.cibw_py_ver }}-${{ inputs.cibw_os }}_${{ inputs.cibw_arch }}"
          CIBW_ARCHS: "${{ inputs.cibw_arch }}"
        with:
          output-dir: wheelhouse
      
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./wheelhouse/*.whl
          name: cibw-${{ inputs.cibw_os }}_${{ inputs.cibw_arch }}
