# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

name: Build
on:
  workflow_dispatch:
    inputs:
      cibw_py_ver:
        type: string
        default: 'cp314'
      publish:
        type: boolean
        default: false

permissions: {}

jobs:
  
  build:
    permissions:
      contents: read  # needed by called workflow
    strategy:
      fail-fast: false
      matrix:
        cibw_os: ["manylinux", "musllinux"]
        cibw_arch: ["x86_64", "i686", "aarch64", "armv7l", "ppc64le", "s390x", "riscv64", "loongarch64"]
    
    uses: ./.github/workflows/build_one.yaml
    with:
      os: ${{ (matrix.cibw_arch == 'aarch64' || matrix.cibw_arch == 'armv7l') && 'ubuntu-26.04-arm' || 'ubuntu-26.04' }}
      cibw_os: ${{ matrix.cibw_os }}
      cibw_arch: ${{ matrix.cibw_arch }}
      cibw_py_ver: ${{ inputs.cibw_py_ver }}
  
  
  sdist:
    name: Craft sdist
    permissions:
      contents: read  # recommended by checkout action
    
    runs-on: ubuntu-slim
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'
          pip-install: build setuptools
      
      - name: Package sdist
        run: python3 -m build -sxn
      
      - name: Upload sdist
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./dist/*.tar.gz
          name: sdist
  
  
  publish:
    name: Publish to PyPI & GH
    needs: [build, sdist]
    if: ${{ inputs.publish && !cancelled() && !contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-slim
    
    environment: release   # PyPI upload via "trusted publishing"
    permissions:
      id-token: write      # PyPI upload via "trusted publishing", and GH attestation
      attestations: write  # GH attestation
      contents: write      # tag push
    
    steps:
      
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true  # zizmor: ignore[artipacked]
      
      - name: Determine version
        id: get_version
        run: |
          VERSION=$(python3 ./utils/get_version.py)
          echo "Determined version $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Download sdist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          name: sdist
      
      - name: Download wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          merge-multiple: true
          pattern: cibw-*
      
      - name: Mask non-PyPI builds
        run: |
          mkdir artifacts/ && cp dist/* -t artifacts/
          shopt -s nullglob
          rm -f dist/*linux_*_loongarch64*.whl
      
      - name: Apply and push repository changes
        run: |
          git config user.email "geisserml@gmail.com"
          git config user.name "geisserml"
          git tag -a "$NEW_VERSION" -m "Autorelease"
          git push --tags
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.version }}
      
      - name: Attest build provenance
        id: provenance
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-path: 'artifacts/*'
      
      - name: Rename provenance file
        run: mv "$SRC_PATH" gn-attestation.json
        env:
          SRC_PATH: ${{ steps.provenance.outputs.bundle-path }}
      
      - name: Publish to GitHub
        run: gh release create "$TAG" --title "$TAG" --verify-tag --fail-on-no-commits $BETA_FLAG $ARTIFACTS
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.get_version.outputs.version }}
          BETA_FLAG: ${{ contains(steps.get_version.outputs.version, 'b') && '--prerelease' || '' }}
          ARTIFACTS: 'artifacts/*.whl artifacts/*.tar.gz gn-attestation.json'
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          packages-dir: dist/
