# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

name: Trigger Release
on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  trigger:
    name: Trigger release workflow
    permissions:
      actions: write  # allow workflow dispatch
    
    runs-on: ubuntu-slim
    steps:
      
      - name: Ensure HEAD of main
        run: |
          EXPECTED_SHA=$(git ls-remote "$REPO_URL" "refs/heads/main" | cut -f1)
          if [[ "$CURRENT_SHA" != "$EXPECTED_SHA" ]]; then
            echo "Current revision is not the HEAD of main: $CURRENT_SHA != $EXPECTED_SHA"
            exit 1
          fi
        env:
          CURRENT_SHA: ${{ github.sha }}
          REPO_URL: ${{ format('{0}/{1}', github.server_url, github.repository) }}
      
      - name: Dispatch build.yaml with GH CLI
        run: echo "$INPUTS" | gh workflow run "$WORKFLOW_FILE" -R "$REPOSITORY" --ref "$REF_NAME" --json
        env:
          WORKFLOW_FILE: build.yaml
          INPUTS: |
            {
              "cibw_py_ver": "cp314",
              "publish": "true",
              "actually_publish": "true"
            }
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          REF_NAME: ${{ github.ref_name }}
